# apiVersion: v1
# kind: Secret
# metadata:
#   name: guestbook-repo
#   namespace: argocd
#   labels:
#     argocd.argoproj.io/secret-type: repository
# stringData:
#   url: https://github.com/argoproj/argocd-example-apps.git
#   description: argocd-app-root-repo

# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: guestbook
#   annotations:
#     notifications.argoproj.io/subscribe.on-sync-succeeded.qq.com: $EMAIL_USER
# spec:
#   destination:
#     name: in-cluster
#     namespace: default
#     server: https://kubernetes.default.svc
#   project: default
#   source:
#     path: kustomize-guestbook
#     repoURL: https://github.com/argoproj/argocd-example-apps.git
#     targetRevision: HEAD
#     targetRevision: main
#   syncPolicy:
#     automated: {}